import "./global.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            P.Tmind
          </Link>
          <Link href="/list">List</Link>
          <Link href="/join">Join</Link>
        </div>

        {children}
      </body>
    </html>
  );
}
